/**
 * This file is autogenerated by
 * You should not edit it manually or your changes might be overwritten.
 */

export default [
  {
    type: 'impl',
    name: 'FollowImpl',
    interface_name: 'coloniz::interfaces::IFollowNFT::IFollowNFT',
  },
  {
    type: 'struct',
    name: 'core::integer::u256',
    members: [
      { name: 'low', type: 'core::integer::u128' },
      { name: 'high', type: 'core::integer::u128' },
    ],
  },
  {
    type: 'enum',
    name: 'core::bool',
    variants: [
      { name: 'False', type: '()' },
      { name: 'True', type: '()' },
    ],
  },
  {
    type: 'struct',
    name: 'coloniz::base::constants::types::FollowData',
    members: [
      {
        name: 'followed_profile_address',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      {
        name: 'follower_profile_address',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      { name: 'follow_timestamp', type: 'core::integer::u64' },
      { name: 'block_status', type: 'core::bool' },
    ],
  },
  {
    type: 'struct',
    name: 'core::byte_array::ByteArray',
    members: [
      { name: 'data', type: 'core::array::Array::<core::bytes_31::bytes31>' },
      { name: 'pending_word', type: 'core::felt252' },
      { name: 'pending_word_len', type: 'core::integer::u32' },
    ],
  },
  {
    type: 'interface',
    name: 'coloniz::interfaces::IFollowNFT::IFollowNFT',
    items: [
      {
        type: 'function',
        name: 'follow',
        inputs: [
          {
            name: 'follower_profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'unfollow',
        inputs: [
          {
            name: 'unfollower_profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'process_block',
        inputs: [
          {
            name: 'follower_profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::bool' }],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'process_unblock',
        inputs: [
          {
            name: 'follower_profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::bool' }],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'get_follower_profile_address',
        inputs: [{ name: 'follow_id', type: 'core::integer::u256' }],
        outputs: [
          { type: 'core::starknet::contract_address::ContractAddress' },
        ],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_follow_timestamp',
        inputs: [{ name: 'follow_id', type: 'core::integer::u256' }],
        outputs: [{ type: 'core::integer::u64' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_follow_data',
        inputs: [{ name: 'follow_id', type: 'core::integer::u256' }],
        outputs: [{ type: 'coloniz::base::constants::types::FollowData' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'is_following',
        inputs: [
          {
            name: 'follower_profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::bool' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'is_blocked',
        inputs: [
          {
            name: 'follower_profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::bool' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_follow_id',
        inputs: [
          {
            name: 'follower_profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_follower_count',
        inputs: [],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'name',
        inputs: [],
        outputs: [{ type: 'core::byte_array::ByteArray' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'symbol',
        inputs: [],
        outputs: [{ type: 'core::byte_array::ByteArray' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'token_uri',
        inputs: [{ name: 'follow_id', type: 'core::integer::u256' }],
        outputs: [{ type: 'core::byte_array::ByteArray' }],
        state_mutability: 'view',
      },
    ],
  },
  {
    type: 'impl',
    name: 'SRC5Impl',
    interface_name: 'openzeppelin_introspection::interface::ISRC5',
  },
  {
    type: 'interface',
    name: 'openzeppelin_introspection::interface::ISRC5',
    items: [
      {
        type: 'function',
        name: 'supports_interface',
        inputs: [{ name: 'interface_id', type: 'core::felt252' }],
        outputs: [{ type: 'core::bool' }],
        state_mutability: 'view',
      },
    ],
  },
  {
    type: 'impl',
    name: 'ERC721Impl',
    interface_name: 'openzeppelin_token::erc721::interface::IERC721',
  },
  {
    type: 'struct',
    name: 'core::array::Span::<core::felt252>',
    members: [
      { name: 'snapshot', type: '@core::array::Array::<core::felt252>' },
    ],
  },
  {
    type: 'interface',
    name: 'openzeppelin_token::erc721::interface::IERC721',
    items: [
      {
        type: 'function',
        name: 'balance_of',
        inputs: [
          {
            name: 'account',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'owner_of',
        inputs: [{ name: 'token_id', type: 'core::integer::u256' }],
        outputs: [
          { type: 'core::starknet::contract_address::ContractAddress' },
        ],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'safe_transfer_from',
        inputs: [
          {
            name: 'from',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          {
            name: 'to',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'token_id', type: 'core::integer::u256' },
          { name: 'data', type: 'core::array::Span::<core::felt252>' },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'transfer_from',
        inputs: [
          {
            name: 'from',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          {
            name: 'to',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'token_id', type: 'core::integer::u256' },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'approve',
        inputs: [
          {
            name: 'to',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'token_id', type: 'core::integer::u256' },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'set_approval_for_all',
        inputs: [
          {
            name: 'operator',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'approved', type: 'core::bool' },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'get_approved',
        inputs: [{ name: 'token_id', type: 'core::integer::u256' }],
        outputs: [
          { type: 'core::starknet::contract_address::ContractAddress' },
        ],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'is_approved_for_all',
        inputs: [
          {
            name: 'owner',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          {
            name: 'operator',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::bool' }],
        state_mutability: 'view',
      },
    ],
  },
  {
    type: 'impl',
    name: 'ERC721CamelOnlyImpl',
    interface_name: 'openzeppelin_token::erc721::interface::IERC721CamelOnly',
  },
  {
    type: 'interface',
    name: 'openzeppelin_token::erc721::interface::IERC721CamelOnly',
    items: [
      {
        type: 'function',
        name: 'balanceOf',
        inputs: [
          {
            name: 'account',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'ownerOf',
        inputs: [{ name: 'tokenId', type: 'core::integer::u256' }],
        outputs: [
          { type: 'core::starknet::contract_address::ContractAddress' },
        ],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'safeTransferFrom',
        inputs: [
          {
            name: 'from',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          {
            name: 'to',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'tokenId', type: 'core::integer::u256' },
          { name: 'data', type: 'core::array::Span::<core::felt252>' },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'transferFrom',
        inputs: [
          {
            name: 'from',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          {
            name: 'to',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'tokenId', type: 'core::integer::u256' },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'setApprovalForAll',
        inputs: [
          {
            name: 'operator',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'approved', type: 'core::bool' },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'getApproved',
        inputs: [{ name: 'tokenId', type: 'core::integer::u256' }],
        outputs: [
          { type: 'core::starknet::contract_address::ContractAddress' },
        ],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'isApprovedForAll',
        inputs: [
          {
            name: 'owner',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          {
            name: 'operator',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::bool' }],
        state_mutability: 'view',
      },
    ],
  },
  {
    type: 'impl',
    name: 'OwnableImpl',
    interface_name: 'openzeppelin_access::ownable::interface::IOwnable',
  },
  {
    type: 'interface',
    name: 'openzeppelin_access::ownable::interface::IOwnable',
    items: [
      {
        type: 'function',
        name: 'owner',
        inputs: [],
        outputs: [
          { type: 'core::starknet::contract_address::ContractAddress' },
        ],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'transfer_ownership',
        inputs: [
          {
            name: 'new_owner',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'renounce_ownership',
        inputs: [],
        outputs: [],
        state_mutability: 'external',
      },
    ],
  },
  {
    type: 'constructor',
    name: 'constructor',
    inputs: [
      {
        name: 'hub',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      {
        name: 'profile_address',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      {
        name: 'admin',
        type: 'core::starknet::contract_address::ContractAddress',
      },
    ],
  },
  {
    type: 'event',
    name: 'openzeppelin_token::erc721::erc721::ERC721Component::Transfer',
    kind: 'struct',
    members: [
      {
        name: 'from',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      {
        name: 'to',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      { name: 'token_id', type: 'core::integer::u256', kind: 'key' },
    ],
  },
  {
    type: 'event',
    name: 'openzeppelin_token::erc721::erc721::ERC721Component::Approval',
    kind: 'struct',
    members: [
      {
        name: 'owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      {
        name: 'approved',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      { name: 'token_id', type: 'core::integer::u256', kind: 'key' },
    ],
  },
  {
    type: 'event',
    name: 'openzeppelin_token::erc721::erc721::ERC721Component::ApprovalForAll',
    kind: 'struct',
    members: [
      {
        name: 'owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      {
        name: 'operator',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      { name: 'approved', type: 'core::bool', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'openzeppelin_token::erc721::erc721::ERC721Component::Event',
    kind: 'enum',
    variants: [
      {
        name: 'Transfer',
        type: 'openzeppelin_token::erc721::erc721::ERC721Component::Transfer',
        kind: 'nested',
      },
      {
        name: 'Approval',
        type: 'openzeppelin_token::erc721::erc721::ERC721Component::Approval',
        kind: 'nested',
      },
      {
        name: 'ApprovalForAll',
        type: 'openzeppelin_token::erc721::erc721::ERC721Component::ApprovalForAll',
        kind: 'nested',
      },
    ],
  },
  {
    type: 'event',
    name: 'openzeppelin_introspection::src5::SRC5Component::Event',
    kind: 'enum',
    variants: [],
  },
  {
    type: 'event',
    name: 'openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred',
    kind: 'struct',
    members: [
      {
        name: 'previous_owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      {
        name: 'new_owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
    ],
  },
  {
    type: 'event',
    name: 'openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted',
    kind: 'struct',
    members: [
      {
        name: 'previous_owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      {
        name: 'new_owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
    ],
  },
  {
    type: 'event',
    name: 'openzeppelin_access::ownable::ownable::OwnableComponent::Event',
    kind: 'enum',
    variants: [
      {
        name: 'OwnershipTransferred',
        type: 'openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred',
        kind: 'nested',
      },
      {
        name: 'OwnershipTransferStarted',
        type: 'openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted',
        kind: 'nested',
      },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::follownft::follownft::Follow::Followed',
    kind: 'struct',
    members: [
      {
        name: 'followed_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'follower_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      { name: 'follow_id', type: 'core::integer::u256', kind: 'data' },
      { name: 'timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::follownft::follownft::Follow::Unfollowed',
    kind: 'struct',
    members: [
      {
        name: 'unfollowed_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'unfollower_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      { name: 'follow_id', type: 'core::integer::u256', kind: 'data' },
      { name: 'timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::follownft::follownft::Follow::FollowerBlocked',
    kind: 'struct',
    members: [
      {
        name: 'followed_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'blocked_follower',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      { name: 'follow_id', type: 'core::integer::u256', kind: 'data' },
      { name: 'timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::follownft::follownft::Follow::FollowerUnblocked',
    kind: 'struct',
    members: [
      {
        name: 'followed_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'unblocked_follower',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      { name: 'follow_id', type: 'core::integer::u256', kind: 'data' },
      { name: 'timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::follownft::follownft::Follow::Event',
    kind: 'enum',
    variants: [
      {
        name: 'ERC721Event',
        type: 'openzeppelin_token::erc721::erc721::ERC721Component::Event',
        kind: 'flat',
      },
      {
        name: 'SRC5Event',
        type: 'openzeppelin_introspection::src5::SRC5Component::Event',
        kind: 'flat',
      },
      {
        name: 'OwnableEvent',
        type: 'openzeppelin_access::ownable::ownable::OwnableComponent::Event',
        kind: 'flat',
      },
      {
        name: 'Followed',
        type: 'coloniz::follownft::follownft::Follow::Followed',
        kind: 'nested',
      },
      {
        name: 'Unfollowed',
        type: 'coloniz::follownft::follownft::Follow::Unfollowed',
        kind: 'nested',
      },
      {
        name: 'FollowerBlocked',
        type: 'coloniz::follownft::follownft::Follow::FollowerBlocked',
        kind: 'nested',
      },
      {
        name: 'FollowerUnblocked',
        type: 'coloniz::follownft::follownft::Follow::FollowerUnblocked',
        kind: 'nested',
      },
    ],
  },
] as const;
