/**
 * This file is autogenerated by
 * You should not edit it manually or your changes might be overwritten.
 */

export default [
  {
    type: 'impl',
    name: 'profileImpl',
    interface_name: 'coloniz::interfaces::IProfile::IProfile',
  },
  {
    type: 'enum',
    name: 'coloniz::base::constants::types::BodyVariants',
    variants: [
      { name: 'BODY1', type: '()' },
      { name: 'BODY2', type: '()' },
      { name: 'BODY3', type: '()' },
      { name: 'BODY4', type: '()' },
      { name: 'BODY5', type: '()' },
      { name: 'BODY6', type: '()' },
      { name: 'BODY7', type: '()' },
    ],
  },
  {
    type: 'enum',
    name: 'coloniz::base::constants::types::ToolVariants',
    variants: [
      { name: 'TOOL1', type: '()' },
      { name: 'TOOL2', type: '()' },
      { name: 'TOOL3', type: '()' },
      { name: 'TOOL4', type: '()' },
      { name: 'TOOL5', type: '()' },
      { name: 'TOOL6', type: '()' },
      { name: 'EMPTY', type: '()' },
    ],
  },
  {
    type: 'enum',
    name: 'coloniz::base::constants::types::BackgroundVariants',
    variants: [
      { name: 'BACKGROUND1', type: '()' },
      { name: 'BACKGROUND2', type: '()' },
      { name: 'BACKGROUND3', type: '()' },
      { name: 'BACKGROUND4', type: '()' },
      { name: 'BACKGROUND5', type: '()' },
      { name: 'EMPTY', type: '()' },
    ],
  },
  {
    type: 'enum',
    name: 'coloniz::base::constants::types::ClothVariants',
    variants: [
      { name: 'CLOTH1', type: '()' },
      { name: 'ClOTH2', type: '()' },
      { name: 'CLOTH3', type: '()' },
      { name: 'CLOTH4', type: '()' },
      { name: 'CLOTH5', type: '()' },
      { name: 'EMPTY', type: '()' },
    ],
  },
  {
    type: 'enum',
    name: 'coloniz::base::constants::types::FaceVariants',
    variants: [
      { name: 'FACE1', type: '()' },
      { name: 'FACE2', type: '()' },
      { name: 'FACE3', type: '()' },
      { name: 'FACE4', type: '()' },
      { name: 'FACE5', type: '()' },
      { name: 'FACE6', type: '()' },
      { name: 'FACE7', type: '()' },
      { name: 'FACE8', type: '()' },
    ],
  },
  {
    type: 'enum',
    name: 'coloniz::base::constants::types::AccessoryVariants',
    variants: [
      { name: 'ACCESSORY1', type: '()' },
      { name: 'ACCESSORY2', type: '()' },
      { name: 'ACCESSORY3', type: '()' },
      { name: 'ACCESSORY4', type: '()' },
      { name: 'ACCESSORY5', type: '()' },
      { name: 'ACCESSORY6', type: '()' },
      { name: 'ACCESSORY7', type: '()' },
      { name: 'EMPTY', type: '()' },
    ],
  },
  {
    type: 'struct',
    name: 'coloniz::base::constants::types::ProfileVariants',
    members: [
      { name: 'body', type: 'coloniz::base::constants::types::BodyVariants' },
      { name: 'tool', type: 'coloniz::base::constants::types::ToolVariants' },
      {
        name: 'background',
        type: 'coloniz::base::constants::types::BackgroundVariants',
      },
      { name: 'cloth', type: 'coloniz::base::constants::types::ClothVariants' },
      { name: 'face', type: 'coloniz::base::constants::types::FaceVariants' },
      {
        name: 'accessory',
        type: 'coloniz::base::constants::types::AccessoryVariants',
      },
    ],
  },
  {
    type: 'struct',
    name: 'core::byte_array::ByteArray',
    members: [
      { name: 'data', type: 'core::array::Array::<core::bytes_31::bytes31>' },
      { name: 'pending_word', type: 'core::felt252' },
      { name: 'pending_word_len', type: 'core::integer::u32' },
    ],
  },
  {
    type: 'struct',
    name: 'core::integer::u256',
    members: [
      { name: 'low', type: 'core::integer::u128' },
      { name: 'high', type: 'core::integer::u128' },
    ],
  },
  {
    type: 'struct',
    name: 'coloniz::base::constants::types::Profile',
    members: [
      {
        name: 'profile_address',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      {
        name: 'profile_owner',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      { name: 'pub_count', type: 'core::integer::u256' },
      { name: 'metadata_URI', type: 'core::byte_array::ByteArray' },
      {
        name: 'follow_nft',
        type: 'core::starknet::contract_address::ContractAddress',
      },
    ],
  },
  {
    type: 'interface',
    name: 'coloniz::interfaces::IProfile::IProfile',
    items: [
      {
        type: 'function',
        name: 'create_profile',
        inputs: [
          {
            name: 'coloniznft_contract_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'registry_hash', type: 'core::felt252' },
          { name: 'implementation_hash', type: 'core::felt252' },
          { name: 'salt', type: 'core::felt252' },
          {
            name: 'profile_variants',
            type: 'coloniz::base::constants::types::ProfileVariants',
          },
        ],
        outputs: [
          { type: 'core::starknet::contract_address::ContractAddress' },
        ],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'set_profile_metadata_uri',
        inputs: [
          {
            name: 'profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'metadata_uri', type: 'core::byte_array::ByteArray' },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'get_profile_metadata',
        inputs: [
          {
            name: 'profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::byte_array::ByteArray' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_profile',
        inputs: [
          {
            name: 'profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'coloniz::base::constants::types::Profile' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_user_publication_count',
        inputs: [
          {
            name: 'profile_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
    ],
  },
  {
    type: 'constructor',
    name: 'constructor',
    inputs: [
      {
        name: 'coloniznft_contract_address',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      {
        name: 'hub_address',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      { name: 'follow_nft_classhash', type: 'core::felt252' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::profile::profile::ProfileComponent::CreatedProfile',
    kind: 'struct',
    members: [
      {
        name: 'owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      {
        name: 'profile_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      { name: 'token_id', type: 'core::integer::u256', kind: 'data' },
      { name: 'timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::profile::profile::ProfileComponent::Event',
    kind: 'enum',
    variants: [
      {
        name: 'CreatedProfile',
        type: 'coloniz::profile::profile::ProfileComponent::CreatedProfile',
        kind: 'nested',
      },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::presets::profile::ColonizProfile::Event',
    kind: 'enum',
    variants: [
      {
        name: 'ProfileEvent',
        type: 'coloniz::profile::profile::ProfileComponent::Event',
        kind: 'flat',
      },
    ],
  },
] as const;
