/**
 * This file is autogenerated by
 * You should not edit it manually or your changes might be overwritten.
 */

export default [
  {
    type: 'impl',
    name: 'joltImpl',
    interface_name: 'coloniz::interfaces::IJolt::IJolt',
  },
  {
    type: 'enum',
    name: 'coloniz::base::constants::types::JoltType',
    variants: [
      { name: 'Tip', type: '()' },
      { name: 'Transfer', type: '()' },
      { name: 'Subscription', type: '()' },
      { name: 'Request', type: '()' },
    ],
  },
  {
    type: 'struct',
    name: 'core::byte_array::ByteArray',
    members: [
      { name: 'data', type: 'core::array::Array::<core::bytes_31::bytes31>' },
      { name: 'pending_word', type: 'core::felt252' },
      { name: 'pending_word_len', type: 'core::integer::u32' },
    ],
  },
  {
    type: 'struct',
    name: 'core::integer::u256',
    members: [
      { name: 'low', type: 'core::integer::u128' },
      { name: 'high', type: 'core::integer::u128' },
    ],
  },
  {
    type: 'enum',
    name: 'core::bool',
    variants: [
      { name: 'False', type: '()' },
      { name: 'True', type: '()' },
    ],
  },
  {
    type: 'struct',
    name: 'coloniz::base::constants::types::JoltParams',
    members: [
      { name: 'jolt_type', type: 'coloniz::base::constants::types::JoltType' },
      {
        name: 'recipient',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      { name: 'memo', type: 'core::byte_array::ByteArray' },
      { name: 'amount', type: 'core::integer::u256' },
      { name: 'expiration_stamp', type: 'core::integer::u64' },
      {
        name: 'subscription_details',
        type: '(core::integer::u256, core::bool, core::integer::u256)',
      },
      {
        name: 'erc20_contract_address',
        type: 'core::starknet::contract_address::ContractAddress',
      },
    ],
  },
  {
    type: 'enum',
    name: 'coloniz::base::constants::types::JoltStatus',
    variants: [
      { name: 'PENDING', type: '()' },
      { name: 'SUCCESSFUL', type: '()' },
      { name: 'EXPIRED', type: '()' },
      { name: 'REJECTED', type: '()' },
      { name: 'FAILED', type: '()' },
    ],
  },
  {
    type: 'struct',
    name: 'coloniz::base::constants::types::JoltData',
    members: [
      { name: 'jolt_id', type: 'core::integer::u256' },
      { name: 'jolt_type', type: 'coloniz::base::constants::types::JoltType' },
      {
        name: 'sender',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      {
        name: 'recipient',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      { name: 'memo', type: 'core::byte_array::ByteArray' },
      { name: 'amount', type: 'core::integer::u256' },
      { name: 'status', type: 'coloniz::base::constants::types::JoltStatus' },
      { name: 'expiration_stamp', type: 'core::integer::u64' },
      { name: 'block_timestamp', type: 'core::integer::u64' },
      {
        name: 'erc20_contract_address',
        type: 'core::starknet::contract_address::ContractAddress',
      },
    ],
  },
  {
    type: 'struct',
    name: 'coloniz::base::constants::types::SubscriptionData',
    members: [
      {
        name: 'creator',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      {
        name: 'fee_address',
        type: 'core::starknet::contract_address::ContractAddress',
      },
      { name: 'amount', type: 'core::integer::u256' },
      {
        name: 'erc20_contract_address',
        type: 'core::starknet::contract_address::ContractAddress',
      },
    ],
  },
  {
    type: 'interface',
    name: 'coloniz::interfaces::IJolt::IJolt',
    items: [
      {
        type: 'function',
        name: 'jolt',
        inputs: [
          {
            name: 'jolt_params',
            type: 'coloniz::base::constants::types::JoltParams',
          },
        ],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'auto_renew',
        inputs: [
          {
            name: 'profile',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'sub_id', type: 'core::integer::u256' },
        ],
        outputs: [{ type: 'core::bool' }],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'fulfill_request',
        inputs: [{ name: 'jolt_id', type: 'core::integer::u256' }],
        outputs: [{ type: 'core::bool' }],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'create_subscription',
        inputs: [
          {
            name: 'fee_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'amount', type: 'core::integer::u256' },
          {
            name: 'erc20_contract_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'update_subscription',
        inputs: [
          { name: 'sub_id', type: 'core::integer::u256' },
          {
            name: 'fee_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'amount', type: 'core::integer::u256' },
          {
            name: 'erc20_contract_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'set_fee_address',
        inputs: [
          {
            name: '_fee_address',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'set_whitelisted_renewers',
        inputs: [
          {
            name: 'renewers',
            type: 'core::array::Array::<core::starknet::contract_address::ContractAddress>',
          },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'remove_whitelisted_renewers',
        inputs: [
          {
            name: 'renewers',
            type: 'core::array::Array::<core::starknet::contract_address::ContractAddress>',
          },
        ],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'cancel_auto_renewal',
        inputs: [{ name: 'sub_id', type: 'core::integer::u256' }],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'get_jolt',
        inputs: [{ name: 'jolt_id', type: 'core::integer::u256' }],
        outputs: [{ type: 'coloniz::base::constants::types::JoltData' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_subscription_data',
        inputs: [{ name: 'subscription_id', type: 'core::integer::u256' }],
        outputs: [
          { type: 'coloniz::base::constants::types::SubscriptionData' },
        ],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_renewal_iterations',
        inputs: [
          {
            name: 'profile',
            type: 'core::starknet::contract_address::ContractAddress',
          },
          { name: 'subscription_id', type: 'core::integer::u256' },
        ],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_fee_address',
        inputs: [],
        outputs: [
          { type: 'core::starknet::contract_address::ContractAddress' },
        ],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'is_whitelisted_renewer',
        inputs: [
          {
            name: 'renewer',
            type: 'core::starknet::contract_address::ContractAddress',
          },
        ],
        outputs: [{ type: 'core::bool' }],
        state_mutability: 'view',
      },
    ],
  },
  {
    type: 'constructor',
    name: 'constructor',
    inputs: [
      {
        name: 'owner',
        type: 'core::starknet::contract_address::ContractAddress',
      },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::jolt::jolt::JoltComponent::Jolted',
    kind: 'struct',
    members: [
      { name: 'jolt_id', type: 'core::integer::u256', kind: 'data' },
      { name: 'jolt_type', type: 'core::felt252', kind: 'data' },
      {
        name: 'sender',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'recipient',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      { name: 'block_timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::jolt::jolt::JoltComponent::JoltRequested',
    kind: 'struct',
    members: [
      { name: 'jolt_id', type: 'core::integer::u256', kind: 'data' },
      { name: 'jolt_type', type: 'core::felt252', kind: 'data' },
      {
        name: 'sender',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'recipient',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'expiration_timestamp',
        type: 'core::integer::u64',
        kind: 'data',
      },
      { name: 'block_timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::jolt::jolt::JoltComponent::JoltRequestFullfilled',
    kind: 'struct',
    members: [
      { name: 'jolt_id', type: 'core::integer::u256', kind: 'data' },
      { name: 'jolt_type', type: 'core::felt252', kind: 'data' },
      {
        name: 'sender',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'recipient',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'expiration_timestamp',
        type: 'core::integer::u64',
        kind: 'data',
      },
      { name: 'block_timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::jolt::jolt::JoltComponent::SubscriptionCreated',
    kind: 'struct',
    members: [
      { name: 'sub_id', type: 'core::integer::u256', kind: 'data' },
      {
        name: 'creator',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'fee_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      { name: 'amount', type: 'core::integer::u256', kind: 'data' },
      {
        name: 'erc20_contract_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      { name: 'block_timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::jolt::jolt::JoltComponent::SubscriptionUpdated',
    kind: 'struct',
    members: [
      { name: 'sub_id', type: 'core::integer::u256', kind: 'data' },
      {
        name: 'creator',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      {
        name: 'fee_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      { name: 'amount', type: 'core::integer::u256', kind: 'data' },
      {
        name: 'erc20_contract_address',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      { name: 'block_timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::jolt::jolt::JoltComponent::AutoRenewalCancelled',
    kind: 'struct',
    members: [
      { name: 'sub_id', type: 'core::integer::u256', kind: 'data' },
      {
        name: 'subscriber',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'data',
      },
      { name: 'block_timestamp', type: 'core::integer::u64', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::jolt::jolt::JoltComponent::Event',
    kind: 'enum',
    variants: [
      {
        name: 'Jolted',
        type: 'coloniz::jolt::jolt::JoltComponent::Jolted',
        kind: 'nested',
      },
      {
        name: 'JoltRequested',
        type: 'coloniz::jolt::jolt::JoltComponent::JoltRequested',
        kind: 'nested',
      },
      {
        name: 'JoltRequestFullfilled',
        type: 'coloniz::jolt::jolt::JoltComponent::JoltRequestFullfilled',
        kind: 'nested',
      },
      {
        name: 'SubscriptionCreated',
        type: 'coloniz::jolt::jolt::JoltComponent::SubscriptionCreated',
        kind: 'nested',
      },
      {
        name: 'SubscriptionUpdated',
        type: 'coloniz::jolt::jolt::JoltComponent::SubscriptionUpdated',
        kind: 'nested',
      },
      {
        name: 'AutoRenewalCancelled',
        type: 'coloniz::jolt::jolt::JoltComponent::AutoRenewalCancelled',
        kind: 'nested',
      },
    ],
  },
  {
    type: 'event',
    name: 'openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred',
    kind: 'struct',
    members: [
      {
        name: 'previous_owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      {
        name: 'new_owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
    ],
  },
  {
    type: 'event',
    name: 'openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted',
    kind: 'struct',
    members: [
      {
        name: 'previous_owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
      {
        name: 'new_owner',
        type: 'core::starknet::contract_address::ContractAddress',
        kind: 'key',
      },
    ],
  },
  {
    type: 'event',
    name: 'openzeppelin_access::ownable::ownable::OwnableComponent::Event',
    kind: 'enum',
    variants: [
      {
        name: 'OwnershipTransferred',
        type: 'openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred',
        kind: 'nested',
      },
      {
        name: 'OwnershipTransferStarted',
        type: 'openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted',
        kind: 'nested',
      },
    ],
  },
  {
    type: 'event',
    name: 'coloniz::presets::jolt::Jolt::Event',
    kind: 'enum',
    variants: [
      {
        name: 'JoltEvent',
        type: 'coloniz::jolt::jolt::JoltComponent::Event',
        kind: 'flat',
      },
      {
        name: 'OwnableEvent',
        type: 'openzeppelin_access::ownable::ownable::OwnableComponent::Event',
        kind: 'flat',
      },
    ],
  },
] as const;
