// Generated by apibara

declare module "apibara/types" {
  interface ApibaraRuntimeConfig {
    colonizIndexer: {
      startingBlock: number,

      streamUrl: string,

      postgresConnectionString: string,

      colonizHubContractAddress: string,
    },
  }
}
export type { };